// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: pinax.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PinaxInternalServiceClient is the client API for PinaxInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PinaxInternalServiceClient interface {
	AuthenticateByKey(ctx context.Context, in *AuthenticateByKeyRequest, opts ...grpc.CallOption) (*AuthenticateByKeyResponse, error)
}

type pinaxInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPinaxInternalServiceClient(cc grpc.ClientConnInterface) PinaxInternalServiceClient {
	return &pinaxInternalServiceClient{cc}
}

func (c *pinaxInternalServiceClient) AuthenticateByKey(ctx context.Context, in *AuthenticateByKeyRequest, opts ...grpc.CallOption) (*AuthenticateByKeyResponse, error) {
	out := new(AuthenticateByKeyResponse)
	err := c.cc.Invoke(ctx, "/eosn.protobuf.v1.PinaxInternalService/AuthenticateByKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PinaxInternalServiceServer is the server API for PinaxInternalService service.
// All implementations must embed UnimplementedPinaxInternalServiceServer
// for forward compatibility
type PinaxInternalServiceServer interface {
	AuthenticateByKey(context.Context, *AuthenticateByKeyRequest) (*AuthenticateByKeyResponse, error)
	mustEmbedUnimplementedPinaxInternalServiceServer()
}

// UnimplementedPinaxInternalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPinaxInternalServiceServer struct {
}

func (UnimplementedPinaxInternalServiceServer) AuthenticateByKey(context.Context, *AuthenticateByKeyRequest) (*AuthenticateByKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthenticateByKey not implemented")
}
func (UnimplementedPinaxInternalServiceServer) mustEmbedUnimplementedPinaxInternalServiceServer() {}

// UnsafePinaxInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PinaxInternalServiceServer will
// result in compilation errors.
type UnsafePinaxInternalServiceServer interface {
	mustEmbedUnimplementedPinaxInternalServiceServer()
}

func RegisterPinaxInternalServiceServer(s grpc.ServiceRegistrar, srv PinaxInternalServiceServer) {
	s.RegisterService(&PinaxInternalService_ServiceDesc, srv)
}

func _PinaxInternalService_AuthenticateByKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateByKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PinaxInternalServiceServer).AuthenticateByKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/eosn.protobuf.v1.PinaxInternalService/AuthenticateByKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PinaxInternalServiceServer).AuthenticateByKey(ctx, req.(*AuthenticateByKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PinaxInternalService_ServiceDesc is the grpc.ServiceDesc for PinaxInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PinaxInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "eosn.protobuf.v1.PinaxInternalService",
	HandlerType: (*PinaxInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AuthenticateByKey",
			Handler:    _PinaxInternalService_AuthenticateByKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pinax.proto",
}
