// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountsInternalServiceClient is the client API for AccountsInternalService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountsInternalServiceClient interface {
	SignUserTransaction(ctx context.Context, in *UserTransactionSignatureRequest, opts ...grpc.CallOption) (*SignedTransaction, error)
	UpdateCreatedAccountTrxId(ctx context.Context, in *UpdateTrxIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateLinkedAccountTrxId(ctx context.Context, in *UpdateTrxIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type accountsInternalServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountsInternalServiceClient(cc grpc.ClientConnInterface) AccountsInternalServiceClient {
	return &accountsInternalServiceClient{cc}
}

func (c *accountsInternalServiceClient) SignUserTransaction(ctx context.Context, in *UserTransactionSignatureRequest, opts ...grpc.CallOption) (*SignedTransaction, error) {
	out := new(SignedTransaction)
	err := c.cc.Invoke(ctx, "/accounts.AccountsInternalService/SignUserTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsInternalServiceClient) UpdateCreatedAccountTrxId(ctx context.Context, in *UpdateTrxIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/accounts.AccountsInternalService/UpdateCreatedAccountTrxId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountsInternalServiceClient) UpdateLinkedAccountTrxId(ctx context.Context, in *UpdateTrxIdRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/accounts.AccountsInternalService/UpdateLinkedAccountTrxId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountsInternalServiceServer is the server API for AccountsInternalService service.
// All implementations must embed UnimplementedAccountsInternalServiceServer
// for forward compatibility
type AccountsInternalServiceServer interface {
	SignUserTransaction(context.Context, *UserTransactionSignatureRequest) (*SignedTransaction, error)
	UpdateCreatedAccountTrxId(context.Context, *UpdateTrxIdRequest) (*emptypb.Empty, error)
	UpdateLinkedAccountTrxId(context.Context, *UpdateTrxIdRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAccountsInternalServiceServer()
}

// UnimplementedAccountsInternalServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAccountsInternalServiceServer struct {
}

func (UnimplementedAccountsInternalServiceServer) SignUserTransaction(context.Context, *UserTransactionSignatureRequest) (*SignedTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignUserTransaction not implemented")
}
func (UnimplementedAccountsInternalServiceServer) UpdateCreatedAccountTrxId(context.Context, *UpdateTrxIdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCreatedAccountTrxId not implemented")
}
func (UnimplementedAccountsInternalServiceServer) UpdateLinkedAccountTrxId(context.Context, *UpdateTrxIdRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLinkedAccountTrxId not implemented")
}
func (UnimplementedAccountsInternalServiceServer) mustEmbedUnimplementedAccountsInternalServiceServer() {
}

// UnsafeAccountsInternalServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountsInternalServiceServer will
// result in compilation errors.
type UnsafeAccountsInternalServiceServer interface {
	mustEmbedUnimplementedAccountsInternalServiceServer()
}

func RegisterAccountsInternalServiceServer(s grpc.ServiceRegistrar, srv AccountsInternalServiceServer) {
	s.RegisterService(&AccountsInternalService_ServiceDesc, srv)
}

func _AccountsInternalService_SignUserTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserTransactionSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsInternalServiceServer).SignUserTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsInternalService/SignUserTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsInternalServiceServer).SignUserTransaction(ctx, req.(*UserTransactionSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsInternalService_UpdateCreatedAccountTrxId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrxIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsInternalServiceServer).UpdateCreatedAccountTrxId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsInternalService/UpdateCreatedAccountTrxId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsInternalServiceServer).UpdateCreatedAccountTrxId(ctx, req.(*UpdateTrxIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountsInternalService_UpdateLinkedAccountTrxId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTrxIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountsInternalServiceServer).UpdateLinkedAccountTrxId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountsInternalService/UpdateLinkedAccountTrxId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountsInternalServiceServer).UpdateLinkedAccountTrxId(ctx, req.(*UpdateTrxIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountsInternalService_ServiceDesc is the grpc.ServiceDesc for AccountsInternalService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountsInternalService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accounts.AccountsInternalService",
	HandlerType: (*AccountsInternalServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignUserTransaction",
			Handler:    _AccountsInternalService_SignUserTransaction_Handler,
		},
		{
			MethodName: "UpdateCreatedAccountTrxId",
			Handler:    _AccountsInternalService_UpdateCreatedAccountTrxId_Handler,
		},
		{
			MethodName: "UpdateLinkedAccountTrxId",
			Handler:    _AccountsInternalService_UpdateLinkedAccountTrxId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "accounts.proto",
}
