name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop,main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_EOSN_DEPLOY_KEY }}"
          git config --global url."git@github.com:pomelo-io".insteadOf "https://github.com/pomelo-io"
          git config --global url."git@github.com:eosnationftw".insteadOf "https://github.com/eosnationftw"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Build
        env:
          GOPRIVATE: github.com/pomelo-io,github.com/eosnationftw
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          go build -v ./...

      - name: Tests
        run: |
          go test -v ./...
