name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop,main ]

jobs:

  build:
    name: "Build & Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_EOSN_DEPLOY_KEY }}"
          git config --global url."git@github.com:pomelo-io".insteadOf "https://github.com/pomelo-io"
          git config --global url."git@github.com:eosnationftw".insteadOf "https://github.com/eosnationftw"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
          check-latest: true
          cache: true
          cache-dependency-path: "**go.sum"

      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Build
        env:
          GOPRIVATE: github.com/pomelo-io,github.com/eosnationftw
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          go build -v ./...

      - name: Run tests in root dir
        run: |
          go test -v ./...

      - name: Run tests in submodules
        run: |
          find . -name go.mod -execdir go test ./... \;

